# Generated by Django 2.0.4 on 2018-05-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0002_auto_20180409_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceMember',
            fields=[
                ('jawbone_id', models.CharField(default='', max_length=65, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(default='', max_length=256)),
                ('refresh_token', models.CharField(default='', max_length=256)),
                ('token_expires', models.DateTimeField(default='2018-05-11 19:52:50+00:00')),
                ('last_updated', models.DateTimeField(default='2018-05-04 19:52:50+00:00')),
                ('last_submitted', models.DateTimeField(default='2018-05-04 19:52:50+00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.OpenHumansMember')),
            ],
        ),
    ]
